task4 finished
kojunsei/kintone_dojo pull request #4
Opened 2023-06-20 04:42 UTC by kojunsei

チェックのほどよろしくお願いいたします。

2023-06-30 04:15 UTC, H-Shira requested changes
お疲れ様です！
少し書き換えの多いレビューを出してしまったので、確認して分からなかったら遠慮なく質問してください。
一緒にやった方が早そうだったらGaroonで打ち合わせ予定入れましょう！

2023-06-30 04:15 UTC, H-Shira commented on task4-1.html
> +document.getElementsByClassName('chk')[0].onclick = () => {
せっかく`const checks`と置いているので、`checks[0].onclick`を使ってみましょう！

2023-06-30 04:15 UTC, H-Shira commented on task4-1.html
> +document.getElementsByClassName('chk')[1].onclick = () => {
1つ目のコメントと同様です

2023-06-30 04:15 UTC, H-Shira commented on task4-1.html
> +};
全種類の計算を出す方法だと、コードも長くなってしまうし、後々条件の変更があった時の対応が大変になってしまいます。
なので、クリックされたら、チェックされてるかどうかを確認し、チェックされていればvalueの値で、されていなければ0で、`price`に加算するのはどうでしょうか。
例えば以下のような書き方です。
```
checks[0].onclick = () => {
if (checks[0].checked) {
      securePrice = checks[0].value * 5;
    } else {
      securePrice = 0;
    }
・・・
```
これでチェックされてるかどうかで`securePrice`に違う値段を入れる処理が出来ました。
この処理をディスクでも同様に行なってください。

2023-06-30 04:15 UTC, H-Shira commented on task4-1.html
> +  }document.getElementById('price').textContent = number;
2つ目のコメントと同様です

2023-06-30 04:15 UTC, H-Shira commented on task4-2.html
> +};
ボタンを押した時に動けばいいので、`document.getElementsByClassName('chk')[0].onclick`や`document.getElementsByClassName('chk')[1].onclick`といった処理は不要です。
`document.getElementById('btn').onclick = () =>`から始めてみてください
例えば以下のような書き方です。
```
document.getElementById('btn').onclick = () =>
if checks[0].checked) {
      priceSec = select1.value * checks[0].value;
    } else {
      priceSec = 0;
    }

    if (checks[1].checked) {
・・・
```
これでセキュアオプション(`priceSec`)とディスク増設の値段を出した後に、3900円も合わせて合計してみましょう。
これで大分スッキリすると思います！

2023-07-03 05:01 UTC, kojunsei commented
コードを書き変えました。お忙しいところ恐縮ですが、
どうぞご確認のほどよろしくお願いいたします。

2023-07-06 06:44 UTC, H-Shira approved these changes
いい感じです！お疲れ様でした〜！

2023-07-06 06:45 UTC, kojunsei commented
ご確認ありがとうございます。

2023-07-07 00:07 UTC, merged